sonar.projectKey=kubecalc
sonar.projectName=kubecalc
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

# Ignore folders that don't contain application source code
sonar.exclusions=**/node_modules/**,**/jenkins/**,**/k8s/**